### PR TITLE
`cargo-psp` workspace support

### LINKED ISSUE #139: cargo-psp tries to build the .prx and EBOOT.PBP for a non-PSP binary in a workspace
# Context
I have a workspace set up like this:
```
.
├── Cargo.toml
├── embedded_frontend/  // Graphic rendering with embedded-graphics
├── pc_app/             // PC-only app
├── psp_app/            // PSP-only app
└── src/                // backend library
```

pc_app and psp_app are binaries while the root crate and embedded_frontend are libraries (both imported by the binary crates).

Cargo.toml workspace:
```
[workspace]
members = ["pc_app", "embedded_frontend", "psp_app"]
```
# Problem

When trying to compile the PSP app from the psp_app directory with `__CARGO_TESTS_ONLY_SRC_ROOT=/path/to/rust/src/ cargo +nightly-2022-06-11 psp --release`, I get the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', cargo-psp/src/fix_imports.rs:27:42
```

Editing the cargo-psp source to add `dbg!(&path.as_ref());` before the panic shows this: `[cargo-psp/src/fix_imports.rs:27] &path.as_ref() = "[my workspace path]/target/mipsel-sony-psp/release/pc_app"`. But the PC app obviously can't be compiled for the PSP, and even if it was, it's not what I'm trying to build here.

In the meantime, I can exclude psp_app from the workspace but this breaks rust-analyzer on psp_app's source files.

I could make a pull request so that cargo-psp doesn't panic if a binary isn't present.

### PR DESCRIPTION
**Pull request by ZetaNumbers**
Fixes #139 #146 

Introduces workspace support, crate examples support. Also fixes `--manifest-path`.

Workspace changes i plan to publish as a separate PR.

### CODE REVIEW

File: cargo-psp/src/main.rs [hunk 1]
```diff
@@ -205,126 +205,100 @@ fn main() {
...
-                    .output()
-                    .expect("failed to run pack-pbp");
-            }
-        }
+    // TODO: Error if no bin is ever found.
+    for elf_path in executables {
+        let prx_path = elf_path.with_extension("prx");
+
+        let sfo_path = elf_path.with_extension("param.sfo");
+        let pbp_path = elf_path.with_extension("eboot.pbp");
```
Comment (overdrivenpotato) [inline cargo-psp/src/main.rs:232]: Let's keep the EBOOT name as `EBOOT.PBP`, and the SFO name as `PARAM.SFO`. As it stands right now, this would require explaining in the README that the `crate_name.eboot.pbp` needs to be renamed to `EBOOT.PBP`. While this does allow multiple PSP executables in a single workspace, it adds friction to all users, in return for a use case that is likely so rare nobody will ever use it.

**Review by overdrivenpotato — CHANGES_REQUESTED** [review]

File: cargo-psp/src/main.rs (hunk 1 above)
Comment (overdrivenpotato) [reply cargo-psp/src/main.rs:232]: Or perhaps it is possible to only do this if multiple binaries are detected?

Comment (sajattack) [reply cargo-psp/src/main.rs:232]: What about something like
/target/mipsel-sony-psp/release/
------------------------------------------bin1/
------------------------------------------------/EBOOT.PBP
------------------------------------------------/bin1.prx
-----------------------------------------------/PARAM.SFO
----------------------------------------bin2/
----------------------------------------------/EBOOT.PBP
----------------------------------------------/bin2.prx
---------------------------------------------/PARAM.SFO

where bin1 and bin2 are the "elf_path"s in the workspace

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs:232]: I would add that vitasdk toolchain for psvita (which is based on pspsdk) uses velf, param-sfo, self and vpk extensions for cmake, while pspsdk assumes there's no such thing as multi executable projects. Vitasdk made this jump so i ask you to do that too.

Comment (sajattack) [reply cargo-psp/src/main.rs:232]: I agree with sofa that what you're proposing adds unnecessary overhead of renaming files for end-users.

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs:232]: Then make a descision.

Comment (overdrivenpotato) [reply cargo-psp/src/main.rs:232]: @ZetaNumbers Let's take things down a notch, there is no need to make snarky comments like that. I have already made a decision in my first comment on this PR: **Let's keep `EBOOT.PBP` for single binary projects.** Having it conditionally rename to `elf_name.eboot.pbp` is fine if there are multiple binaries, I have no preference there.

I understand you are making a purity argument, but you should remember that for a project with incredibly high friction for new users (new hardware, new graphics libraries, new app deployment), having to rename `EBOOT.PBP` every time an application is copied to the memory stick is annoying enough to kill continued iteration. Nobody is writing PSP apps for a living, so anything that makes the process unnecessarily annoying is not useful.

Comment (sajattack) [reply cargo-psp/src/main.rs:232]: Also, while we're trying to cool things off, I want you to know that your contributions are valued, but we need to work together to decide what is best for our users.

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs:232]: What about when switching from a single binary to a workspace and vice versa? I think it should delete the old `EBOOT.BIN`s then. I think we should have uppercase extensions too then, like `hello-world.EBOOT.BIN`.

Also sorry if i was looking snarky there. I didn't meant to, i just don't want to run ahead of the train.

Comment (sajattack) [reply cargo-psp/src/main.rs:232]: > What about when switching from a single binary to a workspace and vice versa?

That's a good catch, but ultimately I don't think it's a usecase worth adding code for. If the user wants to clean up the stale files when they switch back and forth (which will be rare), they can do a `cargo clean`

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs:232]: > > What about when switching from a single binary to a workspace and vice versa?
> 
> That's a good catch, but ultimately I don't think it's a usecase worth adding code for. If the user wants to clean up the stale files when they switch back and forth (which will be rare), they can do a `cargo clean` 

It's not about stale files, but to break the user's setup, if it would ever rely upon outdated files. I remember these "relying upon outdated files" errors to be especially annoying.

Comment (overdrivenpotato) [reply cargo-psp/src/main.rs:232]: Sure, with that said deleting the old EBOOT makes sense in a workspace if you want to implement it.

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs:232]: Also there're multi-bin packages, with main.rs and bin/other.rs. I guess the main binary should remain prefixless, but not the others of course.

> Sure, with that said deleting the old EBOOT makes sense in a workspace if you want to implement it.

I wouldn't say so for the user. But it's easy to implement so, it shouldn't matter?

Comment (overdrivenpotato) [reply cargo-psp/src/main.rs:232]: It doesn't matter to me, you can decide. As long as the original behaviour of `EBOOT.PBP` is preserved for non-workspace projects this PR LGTM.

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs]: Implemented in 8e492398967bf3a7767f325352a90a5cbcb577c6

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs]: Actually this requires some more work to do. Right now it reduces file name on any single executable build, even in the workspace.

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs]: Done

**Comment by ZetaNumbers** [comment]
I tested this PR and it works as expected. It's ready for merge.

**Review by sajattack — APPROVED** [review]
Let's rebase this and try to get it merged :)

**Comment by ZetaNumbers** [comment]
rebase done

**Comment by hatmajster** [comment]
I too confirm that by using this changes with `cargo psp -p <package>` works with a binary package in workspace.

File: cargo-psp/src/main.rs [hunk 2]
```diff
@@ -199,132 +200,148 @@ fn main() {
...
+        .stdout(Stdio::piped())
         .spawn()
         .unwrap();
 
-    let status = process.wait().unwrap();
+    let lone = {
+        let output = Command::new(cargo)
+            .arg("metadata")
+            .arg("--format-version=1")
+            .arg("--offline")
```
Comment (sajattack) [inline cargo-psp/src/main.rs:219]: this flag (--offline) is breaking something in our ci

Comment (sajattack) [reply cargo-psp/src/main.rs:219]: https://ci.mijalkovic.ca/teams/rust-psp/pipelines/rust-psp/jobs/run-tests-for-pr/builds/379.1#L62e61128:60

Comment (ZetaNumbers) [reply cargo-psp/src/main.rs]: deleted in 4e002f1
